version: "3.8"

services:
  secret-pass:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - BLOCK_AMOUNT=10 # default is 100
      - API_KEY=api_key
      # - DEBUG=true
