version: "3.8"

services:
  secret-pass:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - BLOCK_AMOUNT=10 # default is 100
      - API_KEY=95e58e66-9ccf-4665-8961-69bd84e73282
      # - DEBUG=true
